# Generated by Django 5.1.3 on 2024-11-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_supplier_alter_cartitem_cart_alter_orderitem_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="supplier",
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="order",
            name="place_at",
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
