# Generated by Django 5.1.3 on 2024-11-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_cartitem_quantity_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
